PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CLIENTS (
    CPF TEXT PRIMARY KEY,
    PASSWORD TEXT
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID TEXT PRIMARY KEY,
    BALANCE REAL,
    FOREIGN KEY (ID) REFERENCES CLIENTS(CPF)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID TEXT PRIMARY KEY,
    ACCOUNTID TEXT,
    AMOUNT REAL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(Id)
);